### ISSUE TITLE
Arrows invisible in exported SVGs

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#14]
Arrowheads invisible in .svg network export

**Comment by matthiasbock** [comment]
example:
![bug2](https://f.cloud.github.com/assets/1587578/523219/919f658e-c09f-11e2-8c40-b2e86a5c106a.jpg)

**Comment by chaitan3** [comment]
This is a bug with biographer-ui I think. Not sure though. Will have to dig deeper.

**Comment by matthiasbock** [comment]
Other people in TBp had this bug too, so it's pretty sure in biographer.
Possibly a problem with stylesheets, not applying "color:black" onto "arrowhead" or similar.

**Comment by matthiasbock** [comment]
Here another example.

Rules:

<pre>
A = !B
B = C
C = D
</pre>

How it looks like in BooleSim:
![browser](https://f.cloud.github.com/assets/1587578/773617/4b60b56a-e93e-11e2-9e5a-5a3a708129fc.jpg)

How the exported SVG looks like:
![exported](https://f.cloud.github.com/assets/1587578/773614/2df6d3ba-e93e-11e2-9db7-51d7e1868efb.jpg)

And the exported SVG's source code:

<pre>
&lt;svg xmlns="http://www.w3.org/2000/svg" id="graph4" class="interactable interact-draggable interact-gestureable" width="347.74656324414536" height="355.02871700382093" style=""&gt;
    &lt;defs&gt;
        &lt;pattern id="stateVariableLocation" patternUnits="objectBoundingBox" x="0" y="0" width="14" height="14"&gt;
            &lt;path d="M0,14 L14,0 M7,7 L14,14 Z" style="stroke-width:2;stroke:rgb(0,0,0)"&gt;&lt;/path&gt;
        &lt;/pattern&gt;
        &lt;marker id="connectingArc40" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24" class="assignment"&gt;
            &lt;path d="M0,0 S10,10,0,20 L20,10 Z" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc40hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24" class="assignment"&gt;
            &lt;path d="M0,0 S10,10,0,20 L20,10 Z" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc41" orient="auto" refX="25" refY="10" markerWidth="35" markerHeight="20" viewBox="-2 -2 39 24" class="stimulation"&gt;
            &lt;path d="M0,0 L0,20 L10,15 L10,5 L0,0 Z M10,0 L10,20 L25,10Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc41hover" orient="auto" refX="25" refY="10" markerWidth="8.75" markerHeight="20" viewBox="-2 -2 39 24" class="stimulation"&gt;
            &lt;path d="M0,0 L0,20 L10,15 L10,5 L0,0 Z M10,0 L10,20 L25,10Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc42" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24" class="stimulation"&gt;
            &lt;path d="M0,0L20,10L0,20Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc42hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24" class="stimulation"&gt;
            &lt;path d="M0,0L20,10L0,20Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc43" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24"&gt;
            &lt;path d="M0,0L20,10L0,20Z" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc43hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24"&gt;
            &lt;path d="M0,0L20,10L0,20Z" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc44" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24"&gt;
            &lt;path d="" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc44hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24"&gt;
            &lt;path d="" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc45" orient="auto" refX="2" refY="10" markerWidth="20" markerHeight="22" viewBox="-2 -2 24 26"&gt;
            &lt;path d="M0,0 V20 H1 V0 ZM22,0" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc45hover" orient="auto" refX="2" refY="10" markerWidth="5" markerHeight="22" viewBox="-2 -2 24 26"&gt;
            &lt;path d="M0,0 V20 H1 V0 ZM22,0" fill="black" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc46" orient="auto" refX="10" refY="12" markerWidth="10" markerHeight="26" viewBox="-2 -2 14 30" class="necessaryStimulation"&gt;
            &lt;path d="M0,0 V25 M10,0 V25Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc46hover" orient="auto" refX="10" refY="12" markerWidth="2.5" markerHeight="26" viewBox="-2 -2 14 30" class="necessaryStimulation"&gt;
            &lt;path d="M0,0 V25 M10,0 V25Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc47" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24" class="catalysis"&gt;
            &lt;circle cx="10" cy="10" r="10" fill="white" stroke="black"&gt;&lt;/circle&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc47hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24" class="catalysis"&gt;
            &lt;circle cx="10" cy="10" r="10" fill="white" stroke="black"&gt;&lt;/circle&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc48" orient="auto" refX="20" refY="10" markerWidth="20" markerHeight="20" viewBox="-2 -2 24 24" class="control"&gt;
            &lt;path d="M10,0L20,10L10,20L0,10Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc48hover" orient="auto" refX="20" refY="10" markerWidth="5" markerHeight="20" viewBox="-2 -2 24 24" class="control"&gt;
            &lt;path d="M10,0L20,10L10,20L0,10Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc49" orient="auto" refX="25" refY="10" markerWidth="26" markerHeight="26" viewBox="-2 -2 30 30" class="necessaryStimulation"&gt;
            &lt;path d="M0,0 V20 M10,0 L25,10L10,20Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
        &lt;marker id="connectingArc49hover" orient="auto" refX="25" refY="10" markerWidth="6.5" markerHeight="26" viewBox="-2 -2 30 30" class="necessaryStimulation"&gt;
            &lt;path d="M0,0 V20 M10,0 L25,10L10,20Z" fill="white" stroke="black"&gt;&lt;/path&gt;
        &lt;/marker&gt;
    &lt;/defs&gt;
    &lt;style type="text/css"&gt;&lt;/style&gt;
    &lt;g transform="scale(1) translate(0, 0)"&gt;
        &lt;g&gt;
            &lt;g id="A" transform="translate(257.74656324414536,265.02871700382093)" class="rect" style="stroke: #c63fb8;"&gt;
                &lt;path d="M30,0 H45 A15,15 0 0,1 60,15 V45 A15,15 0 0,1 45,60 H15 A15,15 0 0,1 0,45 V15 A15,15 0 0,1 15,0 Z" style="stroke: #000000; stroke-width: 2px; fill: #3390f7;"&gt;&lt;/path&gt;
                &lt;text y="41.5" class=""&gt;
                    &lt;tspan x="24" dy="0" style=""&gt;A&lt;/tspan&gt;
                &lt;/text&gt;
            &lt;/g&gt;
            &lt;g id="B" transform="translate(122.19872893817956,264.4589995636197)" class="rect"&gt;
                &lt;path d="M30,0 H45 A15,15 0 0,1 60,15 V45 A15,15 0 0,1 45,60 H15 A15,15 0 0,1 0,45 V15 A15,15 0 0,1 15,0 Z" style="stroke: #000000; stroke-width: 2px; fill: #daf403;"&gt;&lt;/path&gt;
                &lt;text y="41.5" class=""&gt;
                    &lt;tspan x="24.5" dy="0" style=""&gt;B&lt;/tspan&gt;
                &lt;/text&gt;
            &lt;/g&gt;
            &lt;g id="C" transform="translate(30,165.15967494546203)" class="rect"&gt;
                &lt;path d="M30,0 H45 A15,15 0 0,1 60,15 V45 A15,15 0 0,1 45,60 H15 A15,15 0 0,1 0,45 V15 A15,15 0 0,1 15,0 Z" style="stroke: #000000; stroke-width: 2px; fill: #daf403;"&gt;&lt;/path&gt;
                &lt;text y="41.5" class=""&gt;
                    &lt;tspan x="24" dy="0" style=""&gt;C&lt;/tspan&gt;
                &lt;/text&gt;
            &lt;/g&gt;
            &lt;g id="D" transform="translate(216.21611071901862,60)" class="rect" style="stroke: #3f84c6; cursor: move;"&gt;
                &lt;path d="M30,0 H45 A15,15 0 0,1 60,15 V45 A15,15 0 0,1 45,60 H15 A15,15 0 0,1 0,45 V15 A15,15 0 0,1 15,0 Z" style="stroke: #000000; stroke-width: 2px; fill: #daf403;"&gt;&lt;/path&gt;
                &lt;text y="41.5" class=""&gt;
                    &lt;tspan x="23.5" dy="0" style=""&gt;D&lt;/tspan&gt;
                &lt;/text&gt;
            &lt;/g&gt;
        &lt;/g&gt;
        &lt;g&gt;
            &lt;path id="B -&gt; A" class="line" d="M 187.19872893817956 294.6061071180055 L 252.74656324414536 294.88160944943513" marker-end="url(#connectingArc45)"&gt;&lt;/path&gt;
            &lt;path id="C -&gt; B" class="line" d="M 92.49725539670195 230.15967494546203 L 119.70147354147761 259.4589995636197" marker-end="url(#connectingArc43)"&gt;&lt;/path&gt;
            &lt;path id="D -&gt; C" class="line" d="M 211.21611071901862 109.76514603854449 L 95 175.39452890691754" marker-end="url(#connectingArc43)"&gt;&lt;/path&gt;
        &lt;/g&gt;
    &lt;/g&gt;
&lt;/svg&gt;
</pre>

**Comment by matthiasbock** [comment]
First look, I would say biographer failed to insert content into &lt;style&gt;&lt;/style&gt;.
Especially since in the last group on the bottom the path class is set to "line", which is never defined anywhere in the SVG and the path itself does not contain any stroke/fill color settings.

**Comment by matthiasbock** [comment]
The problem is an unsuccessfull XmlHttpRequest to the stylesheet in css/visualization-svg.css, due to an Access-Control-Allow-Origin error. Replacing the empty style e.g. with &lt;style type="text/css"&gt; .line { stroke: black; } &lt;/style&gt; solves the problem.

<a href="https://github.com/matthiasbock/BooleSim/commit/ce696d1d1e09be59e769b54b8c999e9ffcccf6cc">As of this commit</a>, the stylesheet is hardcoded in biographer-ui.js. Not an elegant solution, but does the job for now.
