### ISSUE TITLE
Creating nodes via Ctrl+Right or Rule editor does not work at once

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#17]
After clicking the Create button, it is possible to add/remove nodes via Rule editor or Ctrl+right click. However, this is not instantly possible when the simulator is started.

Should we leave it that way or rather allow for immediate network editing, even before a network is loaded ?

**Comment by chaitan3** [comment]
When the user first visits the website I think the help dialog should open by default, so that the user is not lost and only after clicking on create the user can start adding/removing nodes.

**Comment by matthiasbock** [comment]
this question is answeared in issue 21
