### ISSUE TITLE
Rules editor -> network update bug

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#18]
It sometime happens, that rules entered in the Rules tab, do not lead to an update of the network. Maybe this goes along with errors in the syntax. Maybe we should add some syntax checking or error messages (?)
Unfortunately I am not aware of a "nice" JavaScript formula editor.

I'm trying to find a reproducable procedure to get this problem ...

**Comment by chaitan3** [comment]
Yes, I thought of adding a syntax checker in the rules editor, but due to time constraints in April, I left that part out. Should be simple enough to code in regex. Need to look for some standard syntax checkers.

**Comment by TillS** [comment]
I agree on the syntax checker. After editing rules, when clicking on Network, the Syntax checker should give out error message when there is a problem.

**Comment by chaitan3** [comment]
I've added a basic syntax checker, please test.
