### ISSUE TITLE
Incorrect rule auto-adding

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#19]
For example

<pre>
a = b
</pre>

leads to automatic addition of

<pre>
b = b
</pre>

and a self-loop arrow in the network, which is incorrect. The state of b should be undefined. Such rules should not be added automatically.

**Comment by matthiasbock** [comment]
In importBooleanNetwork in import.js for every new node a default rule is added to the network "node = node". Same for node = True and node = False.
- meaning: during update the previous node value is set (equal to no update at all)
- however after network update this is graphically interpreted as "node updates itself" (loop)
- this is a correct representation for e.g.  "node = not node", but not for "node = node"
- anyway a network should not be altered by the simulator (no addition/alteration of rules!)

What to do:
- node = True and node = False should not any longer be converted to node = node
- nodes without an update rule should not be added one, but left blank
- node = '', node = True, node = False and node = node should simply be disregarded on update

**Comment by matthiasbock** [comment]
tried to fix/implement this in branch mitophagy with commit 
https://github.com/matthiasbock/BooleSim/commit/0d97f9aff7daa12ff99008242a349346633c2f89

**Comment by chaitan3** [comment]
Thanks for fixing the problem. The commit should be merged to master after good testing. 

The "node = node" solution worked well for simplifying the simulation iteration function, but I see that when the self loops were added it introduced bogus edges.

**Comment by TillS** [comment]
Quick question: Why can't nodes be just True or False without an update rule? They could be considered constant inputs such as a growth factor added to a medium or so. Or is this a problem with the java script syntax for the Update rules? 
But for starters: Does the commited fix work well? If so, we should merge it right?

**Comment by chaitan3** [comment]
The fix is already in master and I've tested it a bit. It works well :). I'm closing the issue.
