### ISSUE TITLE
Export timeseries as SVG

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#2]
feature required for the paper

**Comment by matthiasbock** [comment]
how it could work:
- click Export
- select ( ) Timeseries, below model and graph ...
- save ...

open new tab with svg code, as it is done for the network graph export

**Comment by chaitan3** [comment]
Feature added, please take a look at it.

**Comment by matthiasbock** [comment]
Export works! Awesome!

The font size increases, though. The node name column get's too narrow then:

![Timeseries](https://f.cloud.github.com/assets/1587578/135787/955d94d6-7133-11e2-8024-f5cb7867317f.png)

**Comment by chaitan3** [comment]
Fix committed.
