### ISSUE TITLE
Settings dialog

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#20]
We now have two distinct ways of getting to a network, create and import. As the simulator settings apply to both of them, I suggest we move/copy them from the import dialog to a separate one. Agree?

This settings dialog could also feature buttons for "set all nodes to true" and so on.

**Comment by chaitan3** [comment]
+1, that is a good idea.

**Comment by TillS** [comment]
+1

**Comment by matthiasbock** [comment]
:-)

**Comment by matthiasbock** [comment]
will be addressed in https://github.com/matthiasbock/BooleSim/issues/39
