### ISSUE TITLE
Help instead of empty canvas

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#21]
I herby forward a wish from a co-worker of ours: It would be nice to have a little introductory text instead of the empty white canvas on loading, as he didn't notice that the site has already finished loading - was expecting something to pop up in the big white space ;-)

Should we do that? What should we write?

**Comment by chaitan3** [comment]
Like I've mentioned in the issue: https://github.com/matthiasbock/BooleSim/issues/17
I suggest that the help dialog be displayed by default so that the user knows what to do instantly.

**Comment by TillS** [comment]
I agree with Chaitanya! Let's do it like this!

**Comment by matthiasbock** [comment]
Yes, displaying a help dialog every time the simulator opens is nice for beginners, however annoying in everyday use. Therefore it should be a passive subwindow, which does not block the window and the buttons, and it should vanish, when a network is loaded or created.
