### ISSUE TITLE
Timeseries: empty boxes problem

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#22]
![bug1](https://f.cloud.github.com/assets/1587578/523216/797aef32-c09f-11e2-9ea7-9da8a432dc2c.jpg)

**Comment by chaitan3** [comment]
Tips on reproducing the bug? :).

**Comment by TillS** [comment]
This must be new. I have never come across this bug...Is it a problem with a new version? Maybe reset to a working version?

**Comment by matthiasbock** [comment]
In fact in the recent version it appears to be fixed.
