### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by chaitan3** [matthiasbock/BooleSim#23]
We should all follow the same code quality standards. I suggest that all tabs be in the form of 2 spaces. This is adopted by many open source projects. Every block of code should be exactly 1 tab or 2 spaces right of it's parent block. Currently the tabs and spaces are all mixed and it will take time to switch to this standard.

**Comment by matthiasbock** [comment]
I find it a bit difficult to read code that has only 2 spaces for indentation, therefore I personally prefer tabs (also for my Python projects). It's fine for me to use spaces though, if you prefer them.
What do you think about more, like 4 or 5 spaces ?

**Comment by chaitan3** [comment]
4 spaces are ok with me. That's final then :). There must be some software that auto indents code.

**Comment by matthiasbock** [comment]
We can use http://jsbeautifier.org/. 4 spaces is the default there :-)

**Comment by chaitan3** [comment]
Great job!
