### ISSUE TITLE
ginml import bug

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#24]
When importing an example .ginml file (Boolean Cell Cycle model) (see: http://gin.univ-mrs.fr/GINsim/model_repository/CELL%20CYCLE/Cell_cycle/boolean_cell_cycle.ginml), the network is at first imported in the correct way. However, when clicking on the "Rules" tab, the generated rules are incorrect, including true and false that shouldn't be there. When afterwards clicking on the network view again, the model has changed to the incorrect version where "true" and "false" are interpreted as separate nodes. The same apparently holds for boolnet and jSBGN import as stated by the reviewer. This definitely needs to be corrected!!!
Hand in hand with this bug, goes the bug mentioned by the reviewer as "round trip" that upon importing certain formats, the rules are changed export in booleannet or boolnet format will be incorrect as well.

**Comment by chaitan3** [comment]
I have made a few fixes in the GINML import to fix the above bug. Please test. Note that there will still be some loose "false" in the rules but it will not appear on the graph.

**Comment by TillS** [comment]
Still exactly the same problems!

**Comment by chaitan3** [comment]
It's working on my end. There are 2-3 "false" in the rules tab, but it won't show up in the network.

**Comment by TillS** [comment]
I see! It's the same on my end now too. It's already way better than before like this! However, I think it will be very difficult to sell it to the reviewer that there is still these "falses" in the rules tab because they just don't belong there! But if there's really no way around we will just have to hope ;) One thing I noticed though, is that when including a new node in the rules tab on the right hand side of the equation (one node that wasn't mentioned before), the tool still automatically puts another rule in with the node =True
Example:
Creating the network: 

A=B
B=C

the tool automatically also generates the rule: C=true although apparently it doesn't interpret it now with the new functionality. But this should be removed right?

**Comment by chaitan3** [comment]
Fixed now.

**Comment by chaitan3** [comment]
The above comment is for the C=true issue.
