### ISSUE TITLE
Errors in tool after certain time

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#25]
This issue comprises several sub issues mentioned by the reviewer:
1. When an import file cannot be imported, the software should always give an error message. Best would be to include the reason for the failure and if not known, just say that it couldn't import the file format and "please check the syntax again" or something like that
2. Upon import, the tool sometimes just switches to time course or rules editor when it should stay in the network view...why is that? How can this be fixed?
3. Why does the software start to behave erratically after different imports? How can this be fixed?

**Comment by chaitan3** [comment]
Please post some test cases. A step by step procedure on how to reproduce, this is required for debugging. I know this is time consuming but the help will greatly ease the process of finding the problem and fixing it.

**Comment by TillS** [comment]
For Point number 1: Just import an erroneous network! For instance remove a "=" sign in the import file. The tool then just makes nothing upon import. Another reason to have a good parser to check for consistency!

For Point number 2: Upon clicking "Reset" button, it switches to time course, which I guess is ok. I think he meant that this happens upon importing .zginml which we don't support. So the tool should give an error message saying: .zginml is not supported, please import a supported file type

To point 3:

Example:
1. Imported a .ginml file, network seems correct, clicked on rules, wrong rules, clicked back on network, wrong network. When now clicking create nothing happens. 
Error message: "Uncaught Error: Invalid XML: defaultNode*=defaultNode

**Comment by chaitan3** [comment]
All the above problems should be fixed now, if there are more inconsistencies, please start a new issue.

**Comment by TillS** [comment]
Nice! Very good work! thank you!
