### ISSUE TITLE
Create button warning

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#26]
There should be a warning, whenever the current network view is destroyed: 
1. Upon clicking "create"
2. Upon clicking "import"
3. Upon changing rules in the "Rules" tab and changing back to network view

**Comment by chaitan3** [comment]
I have added the warnings for the above 3 cases. Please check if they are satisfactory.

**Comment by matthiasbock** [comment]
Nice! Somehow these dialogs really create a more professional user experience.
Feels much more like a software for an end user, not at all like some random website JavaScript.
I like it! :-)
