### ISSUE TITLE
Transition from "rules" to "time series" tab

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#29]
It is currently impossible to go directly from the "rules" tab to the "time series" tab. Upon clicking "time series" tab from "rules" tab, it always changes to network view.

**Comment by chaitan3** [comment]
That's because, whenever the user switches away from the rule tab the network needs to be reimported, this is done in case the user has made changes. Now on importing, the network tab needs to be displayed for the import to succeed.

**Comment by TillS** [comment]
Alright, that's understandable, but should still be changed, because it is just not good for intuitive handling and looks to a user like a bug. Isn't there another way to handle this? maybe save the changes in the rules tab and just update the network view the next time the user clicks on network?

**Comment by chaitan3** [comment]
Ok, fix committed.

**Comment by TillS** [comment]
Perfect! works! Thank you!
