### ISSUE TITLE
Setup checkboxes in the import dialog were lost on the way

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#3]
To disable the simulate on-click functionality, there was a checkbox in the import dialog.
It can be disabled by default, but a checkbox to enable it, if required, should be present.

**Comment by chaitan3** [comment]
Fix committed.

**Comment by matthiasbock** [comment]
There were two checkboxes:
- Start simulation after import
- Start simulation on node click

**Comment by chaitan3** [comment]
In my GSoC version only the "Start simulation on node click" was there. Anyways for users that want the start simulation on node click functionality, they can modify that using the settings.js file.

**Comment by matthiasbock** [comment]
We should still add the
- Start simulation after import

checkbox

**Comment by chaitan3** [comment]
Feature added in latest commit.
