### ISSUE TITLE
jSBGN node positions are not re-imported

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/BooleSim#31]
Exporting a network to jSBGN works; it includes node positions.
Example:

<pre>
{
    "sbgnlang": "PD",
    "nodes": [{
        "id": "A",
        "visible": true,
        "data": {
            "cssClasses": ["rect"],
            "x": 800.7725423966185,
            "y": 80,
            "width": 60,
            "height": 60,
            "label": "A"
        },
        "sbo": 245
    }, {
        "id": "B",
        "visible": true,
        "data": {
            "cssClasses": ["rect"],
            "x": 200.7923725876608,
            "y": 130.48633059786516,
            "width": 60,
            "height": 60,
            "label": "B"
        },
        "sbo": 245
    }, {
        "id": "C",
        "visible": true,
        "data": {
            "cssClasses": ["rect"],
            "x": 787.4670172830229,
            "y": 267.87945549358847,
            "width": 60,
            "height": 60,
            "label": "C"
        },
        "sbo": 245
    }, {
        "id": "D",
        "visible": true,
        "data": {
            "cssClasses": ["rect"],
            "x": 192,
            "y": 306.6664647782454,
            "width": 60,
            "height": 60,
            "label": "D"
        },
        "sbo": 245
    }],
    "edges": [{
        "id": "B -> A",
        "visible": true,
        "data": {
            "cssClasses": ["line"]
        },
        "source": "B",
        "target": "A",
        "sbo": 20
    }, {
        "id": "C -> B",
        "visible": true,
        "data": {
            "cssClasses": ["line"]
        },
        "source": "C",
        "target": "B",
        "sbo": 11
    }, {
        "id": "D -> C",
        "visible": true,
        "data": {
            "cssClasses": ["line"]
        },
        "source": "D",
        "target": "C",
        "sbo": 11
    }],
    "rules": {
        "A": "!B",
        "B": "C",
        "C": "D"
    }
}
</pre>

However it seems, on import the node coordinates embedded in jSBGN are not used to position the nodes accordingly on the canvas. The positioning appears random instead. They should be though, because the Export dialog says "Export graph and model", which somehow implies that the next time the user imports his or her network the nodes will be where they were placed.

Side note: jSBGN format is apparently currently not recognized by "infer format".

**Comment by chaitan3** [comment]
I had a look at  the code. There are incompatibilities between the d3 layouter nodes array format and that of jSBGN. Furthermore there is a problem with coordinate scaling. Suppose the jSBGN is exported in a larger screen and imported in a smaller one, the graph will appear to be zoomed in and sparse. Another problem with coordinates is that the values that d3 operates on and what biographer exports in the jSBGN are different and a lot of interconversion will have to be done. 

I know that for the end user we should fix the bug, but the small improvement does not justify the effort.

**Comment by matthiasbock** [comment]
I have now circumvented the problem by disabling d3 layout for jSBGN model import completely. This requires imported jSBGN models to be pre-layouted, but I guess we can assume that in practice the models used with BooleSim anyway are exports from previous sessions with BooleSim (and therefore are layouted) or from software, which does export layouted node positions into jSBGN for us.

<a href="https://github.com/matthiasbock/BooleSim/commit/66b7b8b42f8b0795d4812d8f8fde1981d3381e56">I hereby proudly announce, that as of this commit, jSBGN provides for 100% saving of model graph and rules.</a> :-)
