### ISSUE TITLE
set inital state manually

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#5]
Should be possible to set initial state by hand, either through handing the complete state to the tool or by stopping the simulation completely, then changing the nodes' state through clicking on them and then relaunching the simulation from that new state.

**Comment by matthiasbock** [comment]
Right, see also this issue:
  https://github.com/matthiasbock/BoNeSim/issues/3
We had the functionality to disable simulate-on-click, but lost it somewhere on the way.

Would a checkbox to disable simulate-on-click in the import dialog be sufficient ?

**Comment by chaitan3** [comment]
Fix committed

**Comment by TillS** [comment]
WOW!!!

So many fixes in so little time! Nice Chaitanya! It really works so much
better now with the improvements and is much user friendlier.
Just some minor little things:
1. When CTRL+rightclicking on nodes, we can manipulate the update rule and
   close the window with the little "x" in the upper right but nothing
   happpens when clicking the "cancel" button on the bottom. I think that's a
   really quick fix
2. I don't know why but upon importing files, the "guess format"
   functionality isn't working anymore. I don't think, it's a very important
   feature but as long as it's an option in the "import" button, it should
   work ;)
3. The export functionality is cool but it should be feasible to save the
   files to the user's harddisc and not only open it in the browser...

That's all for the moment. I think the tool is working pretty cool by now.
We should correct the small things and then I guess it's really ready for
takeoff.
And then, once the application note is published we can extend the
functionality of the tool with the ideas we had during GSoC (asynchronous
updating, state space, ...)

Cheers,

Till

2013/2/6 Chaitanya Talnikar notifications@github.com

> Fix committed
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthiasbock/BoNeSim/issues/5#issuecomment-13194352.

## 

Till Scharp
Humboldt University Berlin
Institute for Biology
Theoretical Biophysics
Invalidenstr. 42, 10115 Berlin, Germany

Phone: +49 30 2093 8389
Email: scharptl@biologie.hu-berlin.de till.scharp@gmail.com
           till.scharp@gmail.com

**Comment by TillS** [comment]
Hey guys,

Just realized that although now we have the possibility to turn "simulate
on click" on or off, even if it's turned off and the user changes node
states and wants to simulate then from the new initial state, the time
series shows all the different manipulations that were done although in my
opinion it should only show the initial state that was chosen through
manipulation of the nodes and then the simulation until the steady state.
Is this understandable and easy to implement? Would be important!

Cheers

Till

2013/2/7 Till Scharp till.scharp@googlemail.com

> WOW!!!
> 
> So many fixes in so little time! Nice Chaitanya! It really works so much
> better now with the improvements and is much user friendlier.
> Just some minor little things:
> 1. When CTRL+rightclicking on nodes, we can manipulate the update rule and
>    close the window with the little "x" in the upper right but nothing
>    happpens when clicking the "cancel" button on the bottom. I think that's a
>    really quick fix
> 2. I don't know why but upon importing files, the "guess format"
>    functionality isn't working anymore. I don't think, it's a very important
>    feature but as long as it's an option in the "import" button, it should
>    work ;)
> 3. The export functionality is cool but it should be feasible to save the
>    files to the user's harddisc and not only open it in the browser...
> 
> That's all for the moment. I think the tool is working pretty cool by now.
> We should correct the small things and then I guess it's really ready for
> takeoff.
> And then, once the application note is published we can extend the
> functionality of the tool with the ideas we had during GSoC (asynchronous
> updating, state space, ...)
> 
> Cheers,
> 
> Till
> 
> 2013/2/6 Chaitanya Talnikar notifications@github.com
> 
> > Fix committed
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/matthiasbock/BoNeSim/issues/5#issuecomment-13194352.
> 
> ## 
> 
> Till Scharp
> Humboldt University Berlin
> Institute for Biology
> Theoretical Biophysics
> Invalidenstr. 42, 10115 Berlin, Germany
> 
> Phone: +49 30 2093 8389
> Email: scharptl@biologie.hu-berlin.de till.scharp@gmail.com
>            till.scharp@gmail.com

## 

Till Scharp
Humboldt University Berlin
Institute for Biology
Theoretical Biophysics
Invalidenstr. 42, 10115 Berlin, Germany

Phone: +49 30 2093 8389
Email: scharptl@biologie.hu-berlin.de till.scharp@gmail.com
           till.scharp@gmail.com

**Comment by chaitan3** [comment]
@TillS 
Fixed all the bugs that you've reported.
For the save file functionality in export, it already exists, the new window that is opened can be saved using Ctrl + S. For downloading the file automatically I would have to use the new HTML5 JS File Writer API and I'm not so keen on using that as it is not supported by all browsers.
