### ISSUE TITLE
positive and negative interactions

### ISSUE THREAD

**Issue by hklarner** [matthiasbock/BooleSim#61]
just a comment. In the bioinformatics paper you write

> This interaction can be positive, which biologically corresponds
> to stimulation or activation, or negative, which corresponds to
> inhibition.

but XOR expressions are positive and negative at the same time.
In this network:

```
A = !B && C || B && !C
B = B
C = C
```

both interactions are positive and negative.

**Comment by matthiasbock** [comment]
I know. Thank you.
